import { createClient } from "redis";
import {
  BULL_REDIS_CONFIG_DB,
  BULL_REDIS_CONFIG_HOST,
  BULL_REDIS_CONFIG_PASSWORD,
  BULL_REDIS_CONFIG_PORT,

  REDIS_CONFIG_HOST,
  REDIS_CONFIG_PASSWORD,
  REDIS_CONFIG_USERNAME,
  REDIS_CONFIG_PORT,
  REDIS_CONFIG_DB,
  BULL_REDIS_CONFIG_USERNAME
} from "./env.js";

export const bullMqConnection = {
  host: BULL_REDIS_CONFIG_HOST,
  port: Number(BULL_REDIS_CONFIG_PORT),
  username:BULL_REDIS_CONFIG_USERNAME,
  password: BULL_REDIS_CONFIG_PASSWORD,
  db: Number(BULL_REDIS_CONFIG_DB),
  
}


