import dotenv from "dotenv";

dotenv.config();
export const  {
  PORT,
  MONGO_URI,
  REFRESH_TOKEN_EXPIRES_IN,
  REDIS_CONFIG_HOST,
  REDIS_CONFIG_PORT,
  REDIS_CONFIG_USERNAME,
  REDIS_CONFIG_PASSWORD,
  REDIS_CONFIG_DB,
  BULL_REDIS_CONFIG_HOST,
  BULL_REDIS_CONFIG_PORT,
  BULL_REDIS_CONFIG_USERNAME,
  BULL_REDIS_CONFIG_PASSWORD,
  BULL_REDIS_CONFIG_DB,
} = process.env;
